import type { Workshop } from './types'

export const sharingPrototypes: Workshop = {
  id: 'sharing-prototypes',
  number: 4,
  name: 'Sharing AI Prototypes',
  title: 'Sharing AI Prototypes: A Production Pipeline',
  summary: 'Publish a prototype from AI Studio to GitHub and Vercel, so anyone can open it.',
  guides: [
    {
      file: 'sharing-prototypes/index.md',
      slug: 'sharing-prototypes/',
      name: 'Start here',
      title: 'Sharing AI Prototypes: A Production Pipeline',
      prev: null,
      next: 'sharing-prototypes/accounts',
    },
    {
      file: 'sharing-prototypes/tldr.md',
      slug: 'sharing-prototypes/tldr',
      name: 'TLDR',
      title: 'TLDR: Sharing AI Prototypes',
      // The TLDR is the short route, so it leads straight to Practice.
      prev: 'sharing-prototypes/',
      next: 'sharing-prototypes/practice',
    },
    {
      file: 'sharing-prototypes/accounts.md',
      slug: 'sharing-prototypes/accounts',
      name: 'Accounts',
      title: 'Creating Your Accounts',
      prev: 'sharing-prototypes/',
      next: 'sharing-prototypes/publish-to-github',
    },
    {
      file: 'sharing-prototypes/publish-to-github.md',
      slug: 'sharing-prototypes/publish-to-github',
      name: 'Publish to GitHub',
      title: 'Publishing from AI Studio to GitHub',
      prev: 'sharing-prototypes/accounts',
      next: 'sharing-prototypes/deploy-to-vercel',
    },
    {
      file: 'sharing-prototypes/deploy-to-vercel.md',
      slug: 'sharing-prototypes/deploy-to-vercel',
      name: 'Deploy to Vercel',
      title: 'Deploying to Vercel',
      prev: 'sharing-prototypes/publish-to-github',
      next: 'sharing-prototypes/change-and-share',
    },
    {
      file: 'sharing-prototypes/change-and-share.md',
      slug: 'sharing-prototypes/change-and-share',
      name: 'Change and Share',
      title: 'Changing and Sharing Your Prototype',
      prev: 'sharing-prototypes/deploy-to-vercel',
      next: 'sharing-prototypes/api-key',
    },
    {
      file: 'sharing-prototypes/api-key.md',
      slug: 'sharing-prototypes/api-key',
      name: 'Get an API Key',
      title: 'Getting an API Key',
      prev: 'sharing-prototypes/change-and-share',
      next: 'sharing-prototypes/key-on-vercel',
    },
    {
      file: 'sharing-prototypes/key-on-vercel.md',
      slug: 'sharing-prototypes/key-on-vercel',
      name: 'Add Your Key to Vercel',
      title: 'Adding Your Key to Vercel',
      prev: 'sharing-prototypes/api-key',
      next: 'sharing-prototypes/practice',
    },
    {
      file: 'sharing-prototypes/practice.md',
      slug: 'sharing-prototypes/practice',
      name: 'Practice',
      title: 'Practice: Sharing AI Prototypes',
      prev: 'sharing-prototypes/key-on-vercel',
      next: null,
    },
  ],
  sidebar: (item) => [
    item('sharing-prototypes/'),
    item('sharing-prototypes/tldr'),
    {
      text: 'Guides',
      items: [
        item('sharing-prototypes/accounts'),
        item('sharing-prototypes/publish-to-github'),
        item('sharing-prototypes/deploy-to-vercel'),
        item('sharing-prototypes/change-and-share'),
        item('sharing-prototypes/api-key'),
        item('sharing-prototypes/key-on-vercel'),
      ],
    },
    item('sharing-prototypes/practice'),
  ],
}
